### ISSUE TITLE
Not able to run Hierarchical Cluster Analysis

### ISSUE THREAD

**Issue by Ariel505** [eduard-kazakov/attributeBasedClustering#2]
I was using this shapefile of the field @PERCENTAGE,
with the data range from 0-1. Total data record: 11,127
Somehow QGIS crashes when I run the plugin.

Please download the dataset here: http://tiny.cc/8r774y

QGIS version 3.6.1-Noosa, win7 x86

Cheers

**Comment by eduard-kazakov** [comment]
Hi, and thanks for your feedback. Sorry for long answering, i return back to this plugin only now.
In new version (2.2) with latest QGIS version native hierarchical clustering performs well on your dataset - but very long (unfortunately by design).
I recommend to use native hierarchical clustering only for datasets under 1000-2000 features. For big datasets use K-Means or K-Means 2.
